input_lvs = [
    {
        'X': (0, 1.01, 0.01),
        'name': 'Experience',
        'terms': {
            'Without experience': ('trimf', 0, 0, 0.067),    			
            'Minimum experience': ('trapmf', 0, 0.067, 0.134, 0.201), 			
            'Average experience': ('trapmf', 0.134, 0.201, 0.335, 0.402),	
            'Considerable experience': ('trapmf', 0.268, 0.402, 0.536, 0.67),	
			'Extensive experience': ('trapmf', 0.536, 0.67, 1, 1),		
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Average diplom score',
        'terms': {
            'Satisfactory': ('trapmf', 0, 0, 0.25, 0.5),
            'Good': ('trapmf', 0.25, 0.375, 0.625, 0.75),
            'Excellent': ('trapmf', 0.5, 0.75, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'Professional test',
        'terms': {
            'Low score': ('trapmf', 0, 0, 0.3, 0.5),
            'Medium score': ('trapmf', 0.3, 0.4, 0.6, 0.7),
            'High score': ('trapmf', 0.5, 0.7, 1, 1),
        }
    },

    {
        'X': (0, 1.01, 0.01),
        'name': 'English level',
        'terms': {
            'Basic': ('trapmf', 0, 0, 0.2, 0.4),
            'Pre-Intermediate': ('trapmf', 0.2, 0.3, 0.4, 0.5),
            'Intermediate': ('trimf', 0.4, 0.5, 0.6),
            'Upper-Intermediate': ('trapmf', 0.5, 0.6, 0.7, 0.8),
			'Advanced': ('trapmf', 0.6, 0.8, 1, 1),
        }
    }
]

output_lv = {
    'X': (0, 1.01, 0.01),
    'name': 'Suitability of the candidate',
    'terms': {
        'Not suitable': ('trapmf', 0, 0, 0.1, 0.2),
        'Unlikely suitable': ('trimf', 0, 0.2, 0.4),
        'Maybe suitable': ('trapmf', 0.2, 0.3, 0.4, 0.5),
        'Partially suitable': ('trapmf', 0.4, 0.5, 0.6, 0.7),
        'Probably suitable': ('trapmf', 0.5, 0.7, 0.8, 0.9),
        'Excellent suitable': ('trapmf', 0.7, 0.9, 1, 1),
    }
}


rule_base = [
	(('Without experience', 'Satisfactory', 'Low score', 'Basic'), 'Not suitable'),
	(('Without experience', 'Satisfactory', 'Low score', 'Pre-Intermediate'), 'Unlikely suitable'),
	(('Without experience', 'Satisfactory', 'Low score', 'Intermediate'), 'Unlikely suitable'),
	(('Without experience', 'Satisfactory', 'Low score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Satisfactory', 'Low score', 'Advanced'), 'Maybe suitable'),
	(('Without experience', 'Satisfactory', 'Medium score', 'Basic'), 'Unlikely suitable'),
	(('Without experience', 'Satisfactory', 'Medium score', 'Pre-Intermediate'), 'Unlikely suitable'),
	(('Without experience', 'Satisfactory', 'Medium score', 'Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Satisfactory', 'Medium score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Satisfactory', 'Medium score', 'Advanced'), 'Partially suitable'),
	(('Without experience', 'Satisfactory', 'High score', 'Basic'), 'Maybe suitable'),
	(('Without experience', 'Satisfactory', 'High score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Satisfactory', 'High score', 'Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Satisfactory', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Without experience', 'Satisfactory', 'High score', 'Advanced'), 'Partially suitable'),
	(('Without experience', 'Good', 'Low score', 'Basic'), 'Unlikely suitable'),
	(('Without experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Unlikely suitable'),
	(('Without experience', 'Good', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Good', 'Low score', 'Advanced'), 'Maybe suitable'),
	(('Without experience', 'Good', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Without experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Good', 'Medium score', 'Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Good', 'Medium score', 'Advanced'), 'Partially suitable'),
	(('Without experience', 'Good', 'High score', 'Basic'), 'Maybe suitable'),
	(('Without experience', 'Good', 'High score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Good', 'High score', 'Intermediate'), 'Partially suitable'),
	(('Without experience', 'Good', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Without experience', 'Good', 'High score', 'Advanced'), 'Partially suitable'),
	(('Without experience', 'Excellent', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Without experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Excellent', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Excellent', 'Low score', 'Advanced'), 'Partially suitable'),
	(('Without experience', 'Excellent', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Without experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Without experience', 'Excellent', 'Medium score', 'Intermediate'), 'Partially suitable'),
	(('Without experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Without experience', 'Excellent', 'Medium score', 'Advanced'), 'Partially suitable'),
	(('Without experience', 'Excellent', 'High score', 'Basic'), 'Partially suitable'),
	(('Without experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Without experience', 'Excellent', 'High score', 'Intermediate'), 'Partially suitable'),
	(('Without experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Without experience', 'Excellent', 'High score', 'Advanced'), 'Probably suitable'),
	(('Minimum experience', 'Satisfactory', 'Low score', 'Basic'), 'Unlikely suitable'),
	(('Minimum experience', 'Satisfactory', 'Low score', 'Pre-Intermediate'), 'Unlikely suitable'),
	(('Minimum experience', 'Satisfactory', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'Low score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'Low score', 'Advanced'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'Medium score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'Medium score', 'Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'Medium score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'Medium score', 'Advanced'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'High score', 'Basic'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'High score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'High score', 'Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Satisfactory', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Satisfactory', 'High score', 'Advanced'), 'Partially suitable'),
	(('Minimum experience', 'Good', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Minimum experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Good', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Good', 'Low score', 'Advanced'), 'Maybe suitable'),
	(('Minimum experience', 'Good', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Minimum experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Good', 'Medium score', 'Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Good', 'Medium score', 'Advanced'), 'Partially suitable'),
	(('Minimum experience', 'Good', 'High score', 'Basic'), 'Maybe suitable'),
	(('Minimum experience', 'Good', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Good', 'High score', 'Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Good', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Good', 'High score', 'Advanced'), 'Probably suitable'),
	(('Minimum experience', 'Excellent', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Minimum experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Excellent', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Minimum experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Excellent', 'Low score', 'Advanced'), 'Partially suitable'),
	(('Minimum experience', 'Excellent', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Minimum experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Excellent', 'Medium score', 'Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Excellent', 'Medium score', 'Advanced'), 'Probably suitable'),
	(('Minimum experience', 'Excellent', 'High score', 'Basic'), 'Partially suitable'),
	(('Minimum experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Minimum experience', 'Excellent', 'High score', 'Intermediate'), 'Probably suitable'),
	(('Minimum experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Minimum experience', 'Excellent', 'High score', 'Advanced'), 'Probably suitable'),
	(('Average experience', 'Satisfactory', 'Low score', 'Basic'), 'Unlikely suitable'),
	(('Average experience', 'Satisfactory', 'Low score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Average experience', 'Satisfactory', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Average experience', 'Satisfactory', 'Low score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Average experience', 'Satisfactory', 'Low score', 'Advanced'), 'Maybe suitable'),
	(('Average experience', 'Satisfactory', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Average experience', 'Satisfactory', 'Medium score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Average experience', 'Satisfactory', 'Medium score', 'Intermediate'), 'Maybe suitable'),
	(('Average experience', 'Satisfactory', 'Medium score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Average experience', 'Satisfactory', 'Medium score', 'Advanced'), 'Partially suitable'),
	(('Average experience', 'Satisfactory', 'High score', 'Basic'), 'Maybe suitable'),
	(('Average experience', 'Satisfactory', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Average experience', 'Satisfactory', 'High score', 'Intermediate'), 'Partially suitable'),
	(('Average experience', 'Satisfactory', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Average experience', 'Satisfactory', 'High score', 'Advanced'), 'Partially suitable'),
	(('Average experience', 'Good', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Average experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Average experience', 'Good', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Average experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Average experience', 'Good', 'Low score', 'Advanced'), 'Partially suitable'),
	(('Average experience', 'Good', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Average experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Average experience', 'Good', 'Medium score', 'Intermediate'), 'Partially suitable'),
	(('Average experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Average experience', 'Good', 'Medium score', 'Advanced'), 'Partially suitable'),
	(('Average experience', 'Good', 'High score', 'Basic'), 'Partially suitable'),
	(('Average experience', 'Good', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Average experience', 'Good', 'High score', 'Intermediate'), 'Partially suitable'),
	(('Average experience', 'Good', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Average experience', 'Good', 'High score', 'Advanced'), 'Probably suitable'),
	(('Average experience', 'Excellent', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Average experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Average experience', 'Excellent', 'Low score', 'Intermediate'), 'Partially suitable'),
	(('Average experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Average experience', 'Excellent', 'Low score', 'Advanced'), 'Partially suitable'),
	(('Average experience', 'Excellent', 'Medium score', 'Basic'), 'Partially suitable'),
	(('Average experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Average experience', 'Excellent', 'Medium score', 'Intermediate'), 'Partially suitable'),
	(('Average experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Average experience', 'Excellent', 'Medium score', 'Advanced'), 'Probably suitable'),
	(('Average experience', 'Excellent', 'High score', 'Basic'), 'Partially suitable'),
	(('Average experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Probably suitable'),
	(('Average experience', 'Excellent', 'High score', 'Intermediate'), 'Probably suitable'),
	(('Average experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Average experience', 'Excellent', 'High score', 'Advanced'), 'Excellent suitable'),
	(('Considerable experience', 'Satisfactory', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Considerable experience', 'Satisfactory', 'Low score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Considerable experience', 'Satisfactory', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Considerable experience', 'Satisfactory', 'Low score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Considerable experience', 'Satisfactory', 'Low score', 'Advanced'), 'Maybe suitable'),
	(('Considerable experience', 'Satisfactory', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Considerable experience', 'Satisfactory', 'Medium score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Considerable experience', 'Satisfactory', 'Medium score', 'Intermediate'), 'Maybe suitable'),
	(('Considerable experience', 'Satisfactory', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Satisfactory', 'Medium score', 'Advanced'), 'Partially suitable'),
	(('Considerable experience', 'Satisfactory', 'High score', 'Basic'), 'Maybe suitable'),
	(('Considerable experience', 'Satisfactory', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Satisfactory', 'High score', 'Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Satisfactory', 'High score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Satisfactory', 'High score', 'Advanced'), 'Probably suitable'),
	(('Considerable experience', 'Good', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Considerable experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Considerable experience', 'Good', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Considerable experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Good', 'Low score', 'Advanced'), 'Partially suitable'),
	(('Considerable experience', 'Good', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Considerable experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Good', 'Medium score', 'Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Good', 'Medium score', 'Advanced'), 'Probably suitable'),
	(('Considerable experience', 'Good', 'High score', 'Basic'), 'Partially suitable'),
	(('Considerable experience', 'Good', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Good', 'High score', 'Intermediate'), 'Probably suitable'),
	(('Considerable experience', 'Good', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Considerable experience', 'Good', 'High score', 'Advanced'), 'Probably suitable'),
	(('Considerable experience', 'Excellent', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Considerable experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Excellent', 'Low score', 'Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Excellent', 'Low score', 'Advanced'), 'Probably suitable'),
	(('Considerable experience', 'Excellent', 'Medium score', 'Basic'), 'Partially suitable'),
	(('Considerable experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Considerable experience', 'Excellent', 'Medium score', 'Intermediate'), 'Probably suitable'),
	(('Considerable experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Considerable experience', 'Excellent', 'Medium score', 'Advanced'), 'Probably suitable'),
	(('Considerable experience', 'Excellent', 'High score', 'Basic'), 'Probably suitable'),
	(('Considerable experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Probably suitable'),
	(('Considerable experience', 'Excellent', 'High score', 'Intermediate'), 'Probably suitable'),
	(('Considerable experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Considerable experience', 'Excellent', 'High score', 'Advanced'), 'Excellent suitable'),
	(('Extensive experience', 'Satisfactory', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Extensive experience', 'Satisfactory', 'Low score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Extensive experience', 'Satisfactory', 'Low score', 'Intermediate'), 'Maybe suitable'),
	(('Extensive experience', 'Satisfactory', 'Low score', 'Upper-Intermediate'), 'Maybe suitable'),
	(('Extensive experience', 'Satisfactory', 'Low score', 'Advanced'), 'Partially suitable'),
	(('Extensive experience', 'Satisfactory', 'Medium score', 'Basic'), 'Maybe suitable'),
	(('Extensive experience', 'Satisfactory', 'Medium score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Extensive experience', 'Satisfactory', 'Medium score', 'Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Satisfactory', 'Medium score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Satisfactory', 'Medium score', 'Advanced'), 'Partially suitable'),
	(('Extensive experience', 'Satisfactory', 'High score', 'Basic'), 'Partially suitable'),
	(('Extensive experience', 'Satisfactory', 'High score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Satisfactory', 'High score', 'Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Satisfactory', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Satisfactory', 'High score', 'Advanced'), 'Probably suitable'),
	(('Extensive experience', 'Good', 'Low score', 'Basic'), 'Maybe suitable'),
	(('Extensive experience', 'Good', 'Low score', 'Pre-Intermediate'), 'Maybe suitable'),
	(('Extensive experience', 'Good', 'Low score', 'Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Good', 'Low score', 'Upper-Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Good', 'Low score', 'Advanced'), 'Partially suitable'),
	(('Extensive experience', 'Good', 'Medium score', 'Basic'), 'Partially suitable'),
	(('Extensive experience', 'Good', 'Medium score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Good', 'Medium score', 'Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Good', 'Medium score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Good', 'Medium score', 'Advanced'), 'Probably suitable'),
	(('Extensive experience', 'Good', 'High score', 'Basic'), 'Partially suitable'),
	(('Extensive experience', 'Good', 'High score', 'Pre-Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Good', 'High score', 'Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Good', 'High score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Good', 'High score', 'Advanced'), 'Probably suitable'),
	(('Extensive experience', 'Excellent', 'Low score', 'Basic'), 'Partially suitable'),
	(('Extensive experience', 'Excellent', 'Low score', 'Pre-Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Excellent', 'Low score', 'Intermediate'), 'Partially suitable'),
	(('Extensive experience', 'Excellent', 'Low score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Excellent', 'Low score', 'Advanced'), 'Probably suitable'),
	(('Extensive experience', 'Excellent', 'Medium score', 'Basic'), 'Partially suitable'),
	(('Extensive experience', 'Excellent', 'Medium score', 'Pre-Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Excellent', 'Medium score', 'Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Excellent', 'Medium score', 'Upper-Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Excellent', 'Medium score', 'Advanced'), 'Probably suitable'),
	(('Extensive experience', 'Excellent', 'High score', 'Basic'), 'Probably suitable'),
	(('Extensive experience', 'Excellent', 'High score', 'Pre-Intermediate'), 'Probably suitable'),
	(('Extensive experience', 'Excellent', 'High score', 'Intermediate'), 'Excellent suitable'),
	(('Extensive experience', 'Excellent', 'High score', 'Upper-Intermediate'), 'Excellent suitable'),
	(('Extensive experience', 'Excellent', 'High score', 'Advanced'), 'Excellent suitable'),
]